# -*- coding: utf-8 -*-
"""Witchman/Hill

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JJm59aTJSXiFTCpQsIrR6ffrqrMIDE7E
"""

import numpy as np
n=100
z1=[12,7]
u1=[]
m1=16

for i in range(2,n):
  new_z= ((13*z1[i-1])+(11*z1[i-2])+3)% m1
  z1.append(new_z)
  u1_new = new_z/ m1
  u1.append(u1_new)

#print(z1)
print(u1)

z2= [3,5]
u2= []
m2=17
for i in range(2,n):
  new_z2= ((12*z2[i-1]**2) + (13*z2[i-2]))%m2
  z2.append(new_z2)
  u2_new= new_z2 / m2
  u2.append(u2_new)
#print(z2)
print(u2)

z3= [2,7]
u3= []
m3=15
for i in range(2,n):
  new_z3 = ((z3[i-1]**3) + (z2[i-2]**2))%m3
  z3.append(new_z3)
  u3_new= new_z3 / m3
  u3.append(u3_new)
#print(z3)
print(u3)

u =[]
for i in range (n-2):
    u_new = u1[i] + u2[i] +u3[i]
    u.append(u_new-int(u_new))
    
print(u)

import numpy as np
n=1000
z1=[12,7]
u1=[]
m1=16

for i in range(2,n):
  new_z= ((13*z1[i-1])+(11*z1[i-2])+3)% m1
  z1.append(new_z)
  u1_new = new_z/ m1
  u1.append(u1_new)

#print(z1)
print(u1)

z2= [3,5]
u2= []
m2=17
for i in range(2,n):
  new_z2= ((12*z2[i-1]**2) + (13*z2[i-2]))%m2
  z2.append(new_z2)
  u2_new= new_z2 / m2
  u2.append(u2_new)
#print(z2)
print(u2)

z3= [2,7]
u3= []
m3=15
for i in range(2,n):
  new_z3 = ((z3[i-1]**3) + (z2[i-2]**2))%m3
  z3.append(new_z3)
  u3_new= new_z3 / m3
  u3.append(u3_new)
#print(z3)
print(u3)

u =[]
for i in range (n-2):
    u_new = u1[i] + u2[i] +u3[i]
    u.append(u_new-int(u_new))
    
print(u)

import numpy as np
n=5000
z1=[12,7]
u1=[]
m1=16

for i in range(2,n):
  new_z= ((13*z1[i-1])+(11*z1[i-2])+3)% m1
  z1.append(new_z)
  u1_new = new_z/ m1
  u1.append(u1_new)

#print(z1)
print(u1)

z2= [3,5]
u2= []
m2=17
for i in range(2,n):
  new_z2= ((12*z2[i-1]**2) + (13*z2[i-2]))%m2
  z2.append(new_z2)
  u2_new= new_z2 / m2
  u2.append(u2_new)
#print(z2)
print(u2)

z3= [2,7]
u3= []
m3=15
for i in range(2,n):
  new_z3 = ((z3[i-1]**3) + (z2[i-2]**2))%m3
  z3.append(new_z3)
  u3_new= new_z3 / m3
  u3.append(u3_new)
#print(z3)
print(u3)

u =[]
for i in range (n-2):
    u_new = u1[i] + u2[i] +u3[i]
    u.append(u_new-int(u_new))
    
print(u)

from matplotlib import pyplot as plt
plt.bar(range(len(u)),u)
plt.xlabel('index of random number, i')
plt.ylabel('the random number U')
plt.show()